# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi
bindkey "jk" vi-cmd-mode
bindkey -M vicmd '/' history-incremental-search-backward

# bolt fonts in terminal
export LSCOLORS=ExFxBxDxCxegedabagacad

#bug with git, can be removed soon
export SSH_AUTH_SOCK=0
export HOMEBREW_EDITOR=vim
export TERM=xterm-256color


export PATH=''
export CPATH=''
export LIBRARY_PATH=''
#
case "$OSTYPE" in
  linux*)   export BREW=$HOME/.linuxbrew ;;
  darwin*)  export BREW=/usr/local/Homebrew/ ;;
  win*)     echo "Windows" ;;
  cygwin*)  echo "Cygwin" ;;
  bsd*)     echo "BSD" ;;
  solaris*) echo "SOLARIS" ;;
  *)        echo "unknown: $OSTYPE" ;;
esac


SOURCES=( $HOME/projects/miniconda3 $BREW /usr/local /usr /)

for i in ${SOURCES[*]}; do

    export PATH=$PATH:$i/bin
    export PATH=$PATH:$i/sbin
    export CPATH=$CPATH:$i/include
    export LIBRARY_PATH=$LIBRARY_PATH:$i/lib
    #export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$i/lib

done

#Python environment and settings
export PYTHONWARNINGS="ignore"


alias count="ls | wc -l"
